---
- name: Deploy WAR file to Tomcat 10
  hosts: slave3  
  become: yes
  vars:
    nexus_url: "http://13.127.143.40:8081/#browse/browse:boardgame-artifact:com%2Fjavaproject%2Fdatabase_service_project%2F0.0.5%2Fdatabase_service_project-0.0.5.jar"
    war_file_name: "database_service_project-0.0.5.jar"

  tasks:
    - name: Ensure Tomcat is stopped
      systemd:
        name: "tomcat10"
        state: stopped
        enabled: yes

    - name: Download the WAR file from Nexus
      get_url:
        url: "{{ nexus_url }}"
        dest: "/tmp/database_service_project-0.0.5.jar"
        mode: '0644'

    - name: Deploy the jar file to Tomcat
      copy:
        src: "/tmp/database_service_project-0.0.5.jar"
        dest: "/var/lib/tomcat10/webapps/database_service_project-0.0.5.jar"
        remote_src: yes
        mode: '0644'

    - name: Ensure Tomcat is started
      systemd:
        name: "tomcat10"
        state: started
        enabled: yes

    - name: Clean up temporary WAR file
      file:
        path: "/tmp/database_service_project-0.0.5.jar"
        state: absent

  handlers:
    - name: Restart Tomcat
      systemd:
        name: "tomcat10"
        state: restarted
